### PR TITLE
add a commend

### PR DESCRIPTION
**Pull request by Kail1989**
when capture frames from a camera, you may have errors to run the code as "no symbols loaded for opencv_world320d.dll"

### CODE REVIEW

**Comment by jsxyhelu** [comment]
does this error occur in oepncv_world300?

**Comment by Kail1989** [comment]
I did not run with opencv_world300

**Review by garybradski — COMMENTED** [review]
You possibly have other issues depending on which OS and version you are running on. It's possible it does not return a reliable fps for whatever OS/external dependencies you have. I will try this on my system this weekend, but I don't think this can stand as a general comment in the code.

**Comment by garybradski** [comment]
I think this problem is local to a particular setup.

**Pull request closed without merging**
