### PR TITLE
Create Exercises_5.cpp

### PR DESCRIPTION
**Pull request by jsxyhelu**
Create Exercises of chapter 5

### CODE REVIEW

**Comment by jsxyhelu** [comment]
wait for permit.

**Review by garybradski — APPROVED** [review]
This is generally good. I prefer a little "void help(char** argv) function that tells what each function does when it runs. See, for example: example_15-01.cpp.

**Comment by garybradski** [comment]
See my comment, I prefer a "help function" as in example_15-01.cpp https://github.com/oreillymedia/Learning-OpenCV-3_examples/blob/master/example_15-01.cpp  but this is acceptable now. Thanks!

**Comment by jsxyhelu** [comment]
Great. I'll keep improving。

**Pull request merged**
